ENH: Add bad pixel correction
PlusToolkit/PlusLib pull request #750
Opened 2020-12-15 01:30 UTC by jrojasUNC

CCD cameras usually have "bad pixels" these are either dead pixels, pixels with significantly lower intensities than neighbors, or pixels whose intensity does not scale with exposure time. Resolution cells (for example 4x4 pixels if bin=4) with more than 20% bad pixels are replaced by the median of surrounding cells. 

I have included the DeviceConfig.xml that I used and all of the supporting files here https://sonovolinc-my.sharepoint.com/:u:/g/personal/jrojas_sonovol_com/EQawaRtRG5ZHjtCUgsTQhaMBlHcjiXjfE9vIshpYKmCXwQ?e=Ayk57u

I randomly made up an bad pixel image for testing and it has bad pixels here:
![image](https://user-images.githubusercontent.com/20046115/102154555-a3677a80-3e47-11eb-8b2c-693fcf23a11e.png)

I built SonoPlus and changed the Andor PLUS files and acquired calibration images using the command `AcquireCorrection=C:\Users\JuanRojas\Documents\calibrationImage.png,0,bin,1,1,exposure
`

If the algorithm works the image may look basically the same as without the algorithm because the camera being used may not have many dead pixels so I suggest first changing line 642 of vtkPlusAndorVideoSource to `cvIMG.at<ushort>(resolutionCellIndexY, resolutionCellIndexX) = 0;`. This will write an image where the resolution cells that have bad pixels will be set to zero:
![image](https://user-images.githubusercontent.com/20046115/102154441-67341a00-3e47-11eb-9c4e-0003e6595e09.png)

These images show that the algorithm is correctly identifying the location of the bad pixels from the bad pixel image. It also shows that the algorithm will not correct (in this case make 0) resolution cells where less than 25% of the pixels are bad (bin 4 and bin 8 images).

Reverting the change to make the cells with bad pixels 0 (original state) will produce images that look like ones above but without any black pixels and the regions where there are bad pixels look the same are their surroundings.

2020-12-15 01:48 UTC, jamesobutler commented
cc: @dzenanz for review

2020-12-17 17:33 UTC, dzenanz requested changes
Juan, I will make some changes to this and push them to my fork. Then you can integrate into your fork or we could make a new PR to PlusLib.

2020-12-17 17:33 UTC, dzenanz commented on src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.h
>    /*! Paths to additive and multiplicative bias+dark charge correction images. */
This docstring should be updated

2020-12-17 17:33 UTC, dzenanz commented on src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
> +      if (std::find(resolutionCellsWithBadPixels.begin(), resolutionCellsWithBadPixels.end(), resolutionCellIndex) == resolutionCellsWithBadPixels.end())
I believe this logic could be simplified a little.

2020-12-17 17:33 UTC, dzenanz commented on src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
> +    for (int i = 0; i < badIndicesXY.size(); i++)
This should be done in `SetBadPixelCorrectionImage`, not once per frame.

2020-12-17 17:46 UTC, dzenanz commented on src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
> +    for (int i = 0; i < badIndicesXY.size(); i++)
Now I realize this depends on binning too.

2020-12-17 18:22 UTC, dzenanz commented
@jrojasUNC please check modifications in [my fork](https://github.com/dzenanz/PlusLib/tree/add-bad-pixel-correction).

2020-12-18 14:10 UTC, closed without merging